In [2]:
import numpy as np
import requests
import os
import pandas as pd
from bs4 import BeautifulSoup

In [220]:
#I needed to scrape 8 total pages of stats, so for the first page I seperated my steps so the code would be easier to follow
#but for the rest of the pages I put all of the code in the same cell to speed up the process.

url = "https://www.mlb.com/stats/pitching/games/2021"

page = requests.get(url)

soup = BeautifulSoup(page.content, "html.parser")

In [221]:
#This shows that the code is fair game for us to scrape legally which makes sense since it is a public sports database.

page.status_code

200

In [237]:
#All of the stats are under the table tag

table1 = soup.find("table", class_="bui-table is-desktop-sKqjv9Sb")

In [223]:
#All of the headers were collected here to form the outline of our data

headers = []
for i in table1.find_all("th", scope="col"):
 title = i.text
 headers.append(title)
del headers[0]

In [238]:
#For some reason the names of the players were seperated from the other stats so we make a dataframe here that we can just
#merge with the other stats dataframe.

name = []
for i in table1.find_all("th", scope="row"):
 title = i.text
 name.append(title)
names = pd.DataFrame(name)

In [239]:
mydata = pd.DataFrame(columns = headers)

In [226]:
#Here we fill our dataframe with the actual numbers

for j in table1.find_all("tr")[1:]:
 row_data = j.find_all("td")
 row = [i.text for i in row_data]
 length = len(mydata)
 mydata.loc[length] = row

In [227]:
#Here we merge the names and the stats together

frames = [names, mydata]

result1 = pd.concat(frames, axis=1)
result1

,0,TEAMTEAM,WW,LL,ERAERA,caret-upcaret-downGcaret-upcaret-downG,GSGS,CGCG,SHOSHO,SVSV,...,IPIP,HH,RR,ERER,HRHR,HBHB,BBBB,SOSO,WHIPWHIP,AVGAVG
0,1BryanB ShawShawP1‌‌‌,CLE,6,7,3.49,81,0,0,0,2,...,77.1,69,33,30,10,1,38,71,1.38,.235
1,2TylerT RogersRogersP2‌‌‌,SF,7,1,2.22,80,0,0,0,13,...,81.0,74,23,20,5,5,13,55,1.07,.243
2,3TimT HillHillP3‌‌‌,SD,6,6,3.62,78,0,0,0,1,...,59.2,51,34,24,9,6,23,56,1.24,.230
3,3YusmeiroY PetitPetitP3‌‌‌,OAK,8,3,3.92,78,0,0,0,2,...,78.0,69,35,34,12,1,12,37,1.04,.233
4,5SteveS CishekCishekP5‌‌‌,LAA,0,2,3.42,74,0,0,0,0,...,68.1,61,32,26,2,6,41,64,1.49,.238
5,5HectorH NerisNerisP5‌‌‌,PHI,4,7,3.63,74,0,0,0,12,...,74.1,55,34,30,12,4,32,98,1.17,.202
6,7GiovannyG GallegosGallegosP7‌‌‌,STL,6,5,3.02,73,0,0,0,14,...,80.1,51,28,27,6,6,20,95,0.88,.183
7,8JakeJ BrentzBrentzP8‌‌‌,KC,5,2,3.66,72,0,0,0,2,...,64.0,45,32,26,7,6,37,76,1.28,.197
8,8AdamA CimberCimberP8‌‌‌,TOR,3,4,2.26,72,0,0,0,1,...,71.2,61,24,18,2,7,16,51,1.07,.234
9,8MikeM MayersMayersP8‌‌‌,LAA,5,5,3.84,72,2,0,0,2,...,75.0,71,32,32,11,3,26,90,1.29,.250
10,8HanselH RoblesRoblesP8‌‌‌,BOS,3,5,4.43,72,0,0,0,14,...,69.0,58,39,34,8,5,37,76,1.38,.228
11,8RyneR StanekStanekP8‌‌‌,HOU,3,5,3.42,72,0,0,0,2,...,68.1,46,32,26,8,5,37,83,1.21,.186
12,8BlakeB TreinenTreinenP8‌‌‌,LAD,6,5,1.99,72,0,0,0,7,...,72.1,46,20,16,5,3,25,85,0.98,.179
13,14ScottS BarlowBarlowP14‌‌‌,KC,5,3,2.42,71,0,0,0,16,...,74.1,61,20,20,4,2,28,91,1.20,.223
14,14BradB BoxbergerBoxbergerP14‌‌‌,MIL,5,4,3.34,71,0,0,0,4,...,64.2,44,26,24,8,6,25,83,1.07,.192
15,14GenesisG CabreraCabreraP14‌‌‌,STL,4,5,3.73,71,0,0,0,0,...,70.0,52,31,29,3,5,36,77,1.26,.209
16,14AndrewA ChafinChafinP14‌‌‌,OAK,2,4,1.83,71,0,0,0,5,...,68.2,45,14,14,4,2,19,64,0.93,.186
17,14EmmanuelE ClaseClaseP14‌‌‌,CLE,4,5,1.29,71,0,0,0,24,...,69.2,51,18,10,2,0,16,74,0.96,.195
18,14LukeL JacksonJacksonP14‌‌‌,ATL,2,2,1.98,71,0,0,0,0,...,63.2,45,15,14,6,2,29,70,1.16,.198
19,14WillW SmithSmithP14‌‌‌,ATL,3,7,3.44,71,0,0,0,37,...,68.0,49,27,26,11,5,28,87,1.13,.198
20,14LouL TrivinoTrivinoP14‌‌‌,OAK,7,8,3.18,71,0,0,0,22,...,73.2,58,32,26,5,4,34,67,1.25,.216
21,22AnthonyA BassBassP22‌‌‌,MIA,3,9,3.82,70,1,0,0,0,...,61.1,55,33,26,11,3,24,58,1.29,.241
22,22TylerT KinleyKinleyP22‌‌‌,COL,3,2,4.73,70,0,0,0,0,...,70.1,59,37,37,12,2,26,68,1.21,.223
23,24MiguelM CastroCastroP24‌‌‌,NYM,3,4,3.45,69,2,0,0,0,...,70.1,48,30,27,7,6,43,77,1.29,.189
24,24LiamL HendriksHendriksP24‌‌‌,CWS,8,3,2.54,69,0,0,0,38,...,71.0,45,23,20,11,1,7,113,0.73,.174

In [228]:
#Now we just update the url and the result dataframe numbers and do this for 8 total pages.

url2 = "https://www.mlb.com/stats/pitching/games/2021?page=2"
page = requests.get(url2)

soup = BeautifulSoup(page.content, "html.parser")

table1 = soup.find("table", class_="bui-table is-desktop-sKqjv9Sb")

headers = []
for i in table1.find_all("th", scope="col"):
 title = i.text
 headers.append(title)
del headers[0]

name = []
for i in table1.find_all("th", scope="row"):
 title = i.text
 name.append(title)
names = pd.DataFrame(name)
mydata = pd.DataFrame(columns = headers)
for j in table1.find_all("tr")[1:]:
 row_data = j.find_all("td")
 row = [i.text for i in row_data]
 length = len(mydata)
 mydata.loc[length] = row
frames = [names, mydata]

result2 = pd.concat(frames, axis=1)

In [229]:
url2 = "https://www.mlb.com/stats/pitching/games/2021?page=3"
page = requests.get(url2)

soup = BeautifulSoup(page.content, "html.parser")

table1 = soup.find("table", class_="bui-table is-desktop-sKqjv9Sb")

headers = []
for i in table1.find_all("th", scope="col"):
 title = i.text
 headers.append(title)
del headers[0]

name = []
for i in table1.find_all("th", scope="row"):
 title = i.text
 name.append(title)
names = pd.DataFrame(name)
mydata = pd.DataFrame(columns = headers)
for j in table1.find_all("tr")[1:]:
 row_data = j.find_all("td")
 row = [i.text for i in row_data]
 length = len(mydata)
 mydata.loc[length] = row
frames = [names, mydata]

result3 = pd.concat(frames, axis=1)

In [230]:
url2 = "https://www.mlb.com/stats/pitching/games/2021?page=4"
page = requests.get(url2)

soup = BeautifulSoup(page.content, "html.parser")

table1 = soup.find("table", class_="bui-table is-desktop-sKqjv9Sb")

headers = []
for i in table1.find_all("th", scope="col"):
 title = i.text
 headers.append(title)
del headers[0]

name = []
for i in table1.find_all("th", scope="row"):
 title = i.text
 name.append(title)
names = pd.DataFrame(name)
mydata = pd.DataFrame(columns = headers)
for j in table1.find_all("tr")[1:]:
 row_data = j.find_all("td")
 row = [i.text for i in row_data]
 length = len(mydata)
 mydata.loc[length] = row
frames = [names, mydata]

result4 = pd.concat(frames, axis=1)

In [231]:
url2 = "https://www.mlb.com/stats/pitching/games/2021?page=5"
page = requests.get(url2)

soup = BeautifulSoup(page.content, "html.parser")

table1 = soup.find("table", class_="bui-table is-desktop-sKqjv9Sb")

headers = []
for i in table1.find_all("th", scope="col"):
 title = i.text
 headers.append(title)
del headers[0]

name = []
for i in table1.find_all("th", scope="row"):
 title = i.text
 name.append(title)
names = pd.DataFrame(name)
mydata = pd.DataFrame(columns = headers)
for j in table1.find_all("tr")[1:]:
 row_data = j.find_all("td")
 row = [i.text for i in row_data]
 length = len(mydata)
 mydata.loc[length] = row
frames = [names, mydata]

result5 = pd.concat(frames, axis=1)

In [232]:
url2 = "https://www.mlb.com/stats/pitching/games/2021?page=6"
page = requests.get(url2)

soup = BeautifulSoup(page.content, "html.parser")

table1 = soup.find("table", class_="bui-table is-desktop-sKqjv9Sb")

headers = []
for i in table1.find_all("th", scope="col"):
 title = i.text
 headers.append(title)
del headers[0]

name = []
for i in table1.find_all("th", scope="row"):
 title = i.text
 name.append(title)
names = pd.DataFrame(name)
mydata = pd.DataFrame(columns = headers)
for j in table1.find_all("tr")[1:]:
 row_data = j.find_all("td")
 row = [i.text for i in row_data]
 length = len(mydata)
 mydata.loc[length] = row
frames = [names, mydata]

result6 = pd.concat(frames, axis=1)

In [233]:
url2 = "https://www.mlb.com/stats/pitching/games/2021?page=7"
page = requests.get(url2)

soup = BeautifulSoup(page.content, "html.parser")

table1 = soup.find("table", class_="bui-table is-desktop-sKqjv9Sb")

headers = []
for i in table1.find_all("th", scope="col"):
 title = i.text
 headers.append(title)
del headers[0]

name = []
for i in table1.find_all("th", scope="row"):
 title = i.text
 name.append(title)
names = pd.DataFrame(name)
mydata = pd.DataFrame(columns = headers)
for j in table1.find_all("tr")[1:]:
 row_data = j.find_all("td")
 row = [i.text for i in row_data]
 length = len(mydata)
 mydata.loc[length] = row
frames = [names, mydata]

result7 = pd.concat(frames, axis=1)

In [234]:
url2 = "https://www.mlb.com/stats/pitching/games/2021?page=8"
page = requests.get(url2)

soup = BeautifulSoup(page.content, "html.parser")

table1 = soup.find("table", class_="bui-table is-desktop-sKqjv9Sb")

headers = []
for i in table1.find_all("th", scope="col"):
 title = i.text
 headers.append(title)
del headers[0]

name = []
for i in table1.find_all("th", scope="row"):
 title = i.text
 name.append(title)
names = pd.DataFrame(name)
mydata = pd.DataFrame(columns = headers)
for j in table1.find_all("tr")[1:]:
 row_data = j.find_all("td")
 row = [i.text for i in row_data]
 length = len(mydata)
 mydata.loc[length] = row
frames = [names, mydata]

result8 = pd.concat(frames, axis=1)

In [246]:
#Combine our 8 dataframes together to get our 200 players and 20 stats ordered by number of games played.

frames = [result1, result2, result3, result4, result5, result6, result7, result8]

finalresult = pd.concat(frames, axis=0)
finalresult.rename(columns={0 : "Name","caret-upcaret-downGcaret-upcaret-downG" : "Games"}, inplace=True)
finalresult

,Name,TEAMTEAM,WW,LL,ERAERA,Games,GSGS,CGCG,SHOSHO,SVSV,...,IPIP,HH,RR,ERER,HRHR,HBHB,BBBB,SOSO,WHIPWHIP,AVGAVG
0,1BryanB ShawShawP1‌‌‌,CLE,6,7,3.49,81,0,0,0,2,...,77.1,69,33,30,10,1,38,71,1.38,.235
1,2TylerT RogersRogersP2‌‌‌,SF,7,1,2.22,80,0,0,0,13,...,81.0,74,23,20,5,5,13,55,1.07,.243
2,3TimT HillHillP3‌‌‌,SD,6,6,3.62,78,0,0,0,1,...,59.2,51,34,24,9,6,23,56,1.24,.230
3,3YusmeiroY PetitPetitP3‌‌‌,OAK,8,3,3.92,78,0,0,0,2,...,78.0,69,35,34,12,1,12,37,1.04,.233
4,5SteveS CishekCishekP5‌‌‌,LAA,0,2,3.42,74,0,0,0,0,...,68.1,61,32,26,2,6,41,64,1.49,.238
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20,193NoeN RamirezRamirezP193‌‌‌,ARI,0,2,3.00,38,0,0,0,1,...,36.0,23,14,12,3,3,12,29,0.97,.178
21,193ErvinE SantanaSantanaP193‌‌‌,KC,2,2,4.68,38,2,0,0,0,...,65.1,65,35,34,9,2,22,52,1.33,.259
22,198MattM FosterFosterP198‌‌‌,CWS,2,1,6.00,37,0,0,0,1,...,39.0,43,27,26,9,2,13,40,1.44,.274
23,198CollinC McHughMcHughP198‌‌‌,TB,6,1,1.55,37,7,0,0,1,...,64.0,48,15,11,3,2,12,74,0.94,.207
24,198JoelJ PayampsPayampsP198‌‌‌,KC,1,3,3.40,37,1,0,0,0,...,50.1,44,22,19,6,1,14,38,1.15,.232

In [248]:
#Convert our data to a csv file

finalresult.to_csv('2021PitchingStats.csv',index=False)